name: Java CI and Security

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # JOB 1: Esecuzione e Report dei Test Java
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write # Necessario per pubblicare il report dei test nelle PR

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v6

      - uses: actions/setup-java@v6
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven # Velocizza il download delle dipendenze
      - run: java --version

      - run: mvn dependency:resolve

      - name: Esegui i test con Maven
        run: mvn -B test --file pom.xml

      - name: Test Report
        uses: dorny/test-reporter@v3
        if: ${{ !cancelled() }}       # run this step even if previous step failed
        with:
          name: Report Test JUnit
          path: target/surefire-reports/*.xml
          reporter: java-junit
  # Scansione delle Dipendenze (Librerie)
  dependency-scan:
    name: Scan Dependencies
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Permette di pubblicare i risultati nel tab Security

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v6
      - run: mvn dependency:resolve

      - name: Esegui Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs' # Scansiona il file system (troverà il pom.xml o build.gradle)
          scan-ref: "."
          ignore-unfixed: true
          format: 'sarif' # Formato standard per i report di sicurezza
          output: 'trivy-results.sarif'
          # exit-code: '1'
          severity: 'CRITICAL,HIGH' # Segnala solo i problemi gravi
          cache: 'true'  # on by default
          scanners: "vuln"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
